# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-09-15 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smi_filename', models.CharField(db_column='smiFileName', max_length=200)),
                ('eng_sentence', models.CharField(db_column='engSentence', max_length=500)),
                ('kor_sentence', models.CharField(db_column='korSentence', max_length=500)),
                ('emotion', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
    ]
